### ISSUE TITLE
Cadastro de CD com número de paginas diferente de número retorna cadastro com sucesso, mas não cadastra

### ISSUE THREAD

**Issue by leafah** [lucasnobredev/colecaodemidias#1]
Tentei cadastra um CD e no campo Qtd de Músicas coloquei um texto "ala" e voltou "Mídia Cadastrada", mas não cadastrou nada, nem criticou o campo.

**Comment by nobreweb** [comment]
Corrigido! 
Coloquei o campo para number e o min = 1
